version: '3'

services:
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  db:
      external: true